// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BankCard: typeof import('./src/components/molecules/BankCard/BankCard.vue')['default']
    ChButton: typeof import('./src/components/ch/ChButton/ChButton.vue')['default']
    ChCheckbox: typeof import('./src/components/ch/ChCheckbox/components/ChCheckbox.vue')['default']
    ChDialog: typeof import('./src/components/ch/ChDialog/components/ChDialog.vue')['default']
    ChForm: typeof import('./src/components/ch/ChForm/ChForm.vue')['default']
    ChFormItem: typeof import('./src/components/ch/ChFormItem/ChFormItem.vue')['default']
    ChInput: typeof import('./src/components/ch/ChInput/ChInput.vue')['default']
    ChMessage: typeof import('./src/components/ch/ChMessage/ChMessage.vue')['default']
    ChPagination: typeof import('./src/components/ch/ChPagination/ChPagination.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    IconTemplate: typeof import('./src/components/common/IconTemplate.vue')['default']
    LoginForm: typeof import('./src/components/molecules/Login/LoginForm/LoginForm.vue')['default']
    LoginSendEmail: typeof import('./src/components/molecules/Login/LoginSendEmail/LoginSendEmail.vue')['default']
    NewsCard: typeof import('./src/components/molecules/News/NewsCard.vue')['default']
    NewsInfo: typeof import('./src/components/molecules/News/NewsInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SCard: typeof import('./src/components/molecules/SCard.vue')['default']
    SDialog: typeof import('./src/components/global/SDialog/SDialog.vue')['default']
    SFormItem: typeof import('./src/components/global/SFormItem/SFormItem.vue')['default']
    SFormMessage: typeof import('./src/components/global/SFormMessage/SFormMessage.vue')['default']
    SHeader: typeof import('./src/components/organisms/SHeader/SHeader.vue')['default']
    SInput: typeof import('./src/components/global/SInput/SInput.vue')['default']
    SRecoveryPassword: typeof import('./src/components/molecules/SRecoveryPassword/SRecoveryPassword.vue')['default']
    SSelect: typeof import('./src/components/global/SSelect/SSelect.vue')['default']
    SSelectCountry: typeof import('./src/components/molecules/SSelectCountry.vue')['default']
    SSidebar: typeof import('./src/components/organisms/SSidebar/SSidebar.vue')['default']
    SSwiper: typeof import('./src/components/molecules/SSwiper/SSwiper.vue')['default']
    STag: typeof import('./src/components/global/STag/STag.vue')['default']
    SupportContent: typeof import('./src/components/molecules/SupportContent.vue')['default']
    TaskAdd: typeof import('./src/components/Task/TaskAdd/TaskAdd.vue')['default']
    TaskCard: typeof import('./src/components/Task/TaskCard/TaskCard.vue')['default']
  }
}
