version: '3.8'

services:
  web:
    container_name: blog-web
    image: nest-js-dev
    env_file: .env
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/data
      - /usr/src/data/node_modules
    restart: unless-stopped

  db:
    container_name: blog-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  nginx:
    container_name: blog-nginx
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=127.0.0.1
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
      - blog-web
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  postgres_data: