version: '3.8'

services:
  blog-web:
    container_name: web-dev
    image: nest-js-dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  blog-db:
    container_name: blog-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 15s
      retries: 5

  blog-nginx:
    container_name: blog-nginx
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=127.0.0.1
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
      - blog-web
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  postgres_data: